"""Tests for the generated agent registry (agents/agent_registry.yaml).

The registry is generated by scripts/build_agent_registry.py; these tests fail when it is
stale, incomplete, or points at files that do not exist.
"""

from __future__ import annotations

import importlib.util
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "build_agent_registry.py"
REGISTRY = ROOT / "agents" / "agent_registry.yaml"
FOUR = ("README.md", "instructions.md", "tasks.md", "prompt.md")
LEGACY = ("orchestrator-agent", "data-prep-agent", "sql-integration-agent", "tableau-dashboard-agent",
          "reporting-agent", "quality-guard-agent")


def _builder():
    spec = importlib.util.spec_from_file_location("build_agent_registry", SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _entries():
    """Parse the registry through the generator's own data (the file is JSON-scalar YAML)."""
    return _builder().entries()


def test_registry_is_current():
    assert REGISTRY.read_text(encoding="utf-8") == _builder().render(), \
        "stale: run python3 scripts/build_agent_registry.py"


def test_every_public_agent_is_listed_exactly_once():
    on_disk = sorted(p.parent.relative_to(ROOT / "agents").as_posix() for p in (ROOT / "agents").rglob("prompt.md"))
    listed = re.findall(r'^  - name: (".*")$', REGISTRY.read_text(encoding="utf-8"), re.M)
    names = [json.loads(n) for n in listed]
    assert names == on_disk
    assert len(names) == len(set(names)) >= 200


def test_entries_are_complete_and_paths_exist():
    for e in _entries():
        d = ROOT / e["path"]
        assert d.is_dir(), e["name"]
        for f in FOUR:
            assert (d / f).is_file(), (e["name"], f)
        assert e["purpose"].strip() and not e["purpose"].endswith("…"), e["name"]
        assert e["inputs"] and e["outputs"], e["name"]
        assert e["category"] == (e["name"].split("/")[0] if "/" in e["name"] else "root")
        if "skill_path" in e:
            assert (ROOT / e["skill_path"]).is_file(), e["name"]


def test_skill_files_are_all_registered_and_legacy_paths_are_fixed():
    skills = sorted(p.parent.relative_to(ROOT / "agents").as_posix() for p in (ROOT / "agents").rglob("SKILL.md")
                    if (p.parent / "prompt.md").is_file())
    with_skill = sorted(e["name"] for e in _entries() if "skill_path" in e)
    assert with_skill == skills and len(skills) >= 8
    text = REGISTRY.read_text(encoding="utf-8")
    assert "skills_library" not in text.split("agents:", 1)[1]        # the old, nonexistent directory


def test_legacy_entries_keep_their_machine_interface():
    by = {e["name"]: e for e in _entries()}
    for name in LEGACY:
        assert name in by and by[name]["interface"]["inputs"] and by[name]["interface"]["outputs"]
    assert by["orchestrator-agent"]["interface"]["inputs"] == ["natural_language_intent", "system_context"]


def test_venture_agents_carry_their_decision_path_class():
    cov = json.loads((ROOT / "knowledge/venture_intelligence/coverage.json").read_text(encoding="utf-8"))
    expected = {a["path"].replace("agents/", "", 1): a["decision_path_class"] for a in cov["agents"] if a.get("path")}
    by = {e["name"]: e for e in _entries()}
    assert expected, "no built venture agents found"
    for name, cls in expected.items():
        assert by[name]["decision_path_class"] == cls, name
    assert by["venture_intelligence/ownership_screen"]["decision_path_class"] == "sovereign_adjacent"
    assert by["venture_intelligence/hiring_signal_analyst"]["decision_path_class"] == "person_adjacent"
    assert "decision_path_class" not in by["risk"]


def test_generation_is_deterministic():
    b = _builder()
    assert b.render() == b.render()


def test_check_mode_flags_a_stale_registry(tmp_path, monkeypatch):
    b = _builder()
    stale = tmp_path / "agent_registry.yaml"
    stale.write_text("agents: []\n", encoding="utf-8")
    monkeypatch.setattr(b, "REGISTRY", stale)
    assert b.main(["--check"]) == 1
    assert b.main([]) == 0 and stale.read_text(encoding="utf-8") == b.render()
    assert b.main(["--check"]) == 0
