"""Select, write, lock and verify the vendored tree. Spec 0100 REQ-001-REQ-004, REQ-007, NFR-002, NFR-003, NFR-005.

``plan_sync`` applies the allowlist to a source snapshot, refuses unsafe files, and computes the change summary against
the current lock without writing anything. ``write_sync`` writes the plan: upstream files byte for byte, two
QuantSmith-owned files (an overlay ``.claude-plugin/plugin.json`` and a provenance ``README.md``), and the lock. The
output is a pure function of (source files, commit, allowlist, sync date), so a re-run produces no diff (NFR-002).

``verify`` re-checks the vendored tree, the lock, the config and the Claude Code manifests, without network, and
returns findings as strings; the ``agent-skills`` gate prints them.
"""

from __future__ import annotations

import datetime as dt
import hashlib
import json
import os
import re
import shutil
import stat
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

from .config import CONFLICTING, Config
from .source import Snapshot

LOCK_SCHEMA = 1
OWNED = (".claude-plugin/plugin.json", "README.md")
CITATION_RE = re.compile(r"vendor/agent-skills/skills/([A-Za-z0-9._-]+)/SKILL\.md")
FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)


def sha256(data: bytes) -> str:
    return "sha256:" + hashlib.sha256(data).hexdigest()


def tree_hash(files: dict[str, str]) -> str:
    h = hashlib.sha256()
    for path in sorted(files):
        h.update(f"{path}\0{files[path]}\n".encode())
    return h.hexdigest()


def dump_json(obj) -> str:
    return json.dumps(obj, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def item_of(path: str) -> str:
    """The reviewable unit a file belongs to: ``skills/<name>`` for skill files, the path itself otherwise."""
    parts = path.split("/")
    return "/".join(parts[:2]) if parts[0] == "skills" and len(parts) > 2 else path


@dataclass
class SyncPlan:
    files: dict[str, bytes]
    lock: dict
    owned: dict[str, bytes]
    problems: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    changes: dict[str, dict[str, list[str]]] = field(default_factory=dict)

    @property
    def ok(self) -> bool:
        return not self.problems

    def summary(self) -> dict:
        return {
            "ok": self.ok,
            "commit": self.lock.get("commit"),
            "plugin_version": self.lock.get("plugin_version"),
            "version": self.lock.get("version"),
            "files": len(self.files),
            "bytes": sum(len(b) for b in self.files.values()),
            "changes": self.changes,
            "problems": self.problems,
            "warnings": self.warnings,
        }


def _select(cfg: Config, snap: Snapshot) -> tuple[dict[str, object], list[str]]:
    chosen: dict[str, object] = {}
    problems: list[str] = []
    for item in cfg.selection():
        if cfg.is_excluded(item) is not None:
            problems.append(f"{item}: selected by a group but listed in excluded; remove it from one of them")
            continue
        matched = [p for p in snap.files if (p.startswith(item) if item.endswith("/") else p == item)]
        if not matched:
            problems.append(f"{item}: allowlisted but not present in the source")
        for p in matched:
            if cfg.is_excluded(p) is None:
                chosen[p] = snap.files[p]
    return chosen, problems


def _safety(cfg: Config, chosen: dict) -> list[str]:
    problems = []
    for p, e in sorted(chosen.items()):
        if e.unsafe_name:
            problems.append(f"{p}: unsafe path in archive (absolute or '..')")
        elif e.kind == "symlink":
            problems.append(f"{p}: symlink refused")
        elif e.kind != "file":
            problems.append(f"{p}: not a regular file; refused")
        elif e.mode & (stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH):
            problems.append(f"{p}: executable file refused (vendored content is never run)")
        elif e.size > cfg.max_file_bytes or e.data is None:
            problems.append(f"{p}: {e.size} bytes exceeds the {cfg.max_file_bytes}-byte cap")
    return problems


def overlay_manifest(cfg: Config, lock: dict, has_commands: bool) -> bytes:
    manifest = {
        "name": cfg.plugin_name,
        "version": lock["version"],
        "description": (f"Pinned, allowlisted subset of {cfg.upstream} (via {cfg.fork}) for QuantSmith, spec 0100. "
                        "Generated by quantsmith-agent-skills sync; do not edit."),
        "author": {"name": "Addy Osmani"},
        "license": "MIT",
        "skills": "./skills",
    }
    if has_commands:
        manifest["commands"] = ["./.claude/commands"]
    # No "agents" key: an explicit list loads no agents in Claude Code 2.1.292 (validation.md, T-001 check 8);
    # default discovery of ./agents/ does.
    return dump_json(manifest).encode()


def provenance_readme(cfg: Config, lock: dict) -> bytes:
    commit = lock["commit"] or "none (unpinned directory source)"
    groups = ", ".join(lock["groups"])
    text = f"""# Vendored agent-skills (generated, do not edit)

This directory is a pinned, allowlisted subset of [{cfg.upstream}](https://github.com/{cfg.upstream}), MIT-licensed,
copyright Addy Osmani (see `LICENSE`). QuantSmith takes it from its fork `{cfg.fork}`.

- Commit: `{commit}`
- Upstream plugin version: `{lock["plugin_version"]}`
- Groups: {groups}
- Lock: `{cfg.raw["lock"]}`

Every file except this README and `.claude-plugin/plugin.json` is byte-identical to upstream, and its SHA-256 is in the
lock. Do not edit these files. Fix problems in the fork, then re-sync:

    quantsmith-agent-skills diff --source <local clone> --ref <sha>
    quantsmith-agent-skills sync --source <local clone> --ref <sha>

Usage, precedence and exclusions: `instructions/agent_skills.md`. Spec: `specs/0100-agent-skills-upstream-integration/`.
"""
    return text.encode()


def read_lock(cfg: Config) -> dict | None:
    if not cfg.lock_path.is_file():
        return None
    return json.loads(cfg.lock_path.read_text(encoding="utf-8"))


def _changes(old: dict[str, str], new: dict[str, str]) -> dict[str, dict[str, list[str]]]:
    out: dict[str, dict[str, list[str]]] = {}
    for p in sorted(set(old) | set(new)):
        if p in old and p in new and old[p] == new[p]:
            continue
        kind = "added" if p not in old else "removed" if p not in new else "modified"
        out.setdefault(item_of(p), {}).setdefault(kind, []).append(p)
    return out


def plan_sync(cfg: Config, snap: Snapshot, today: dt.date | None = None) -> SyncPlan:
    chosen, problems = _select(cfg, snap)
    problems += _safety(cfg, chosen)
    files = {p: e.data for p, e in chosen.items() if e.kind == "file" and e.data is not None}
    hashes = {p: sha256(b) for p, b in files.items()}
    upstream_version = snap.plugin_version or "0.0.0"
    th = tree_hash(hashes)[:8]
    pin = snap.commit[:7] if snap.commit else "local"
    lock = {
        "schema": LOCK_SCHEMA,
        "upstream": cfg.upstream,
        "fork": cfg.fork,
        "commit": snap.commit,
        "source_kind": snap.kind,
        "plugin_version": upstream_version,
        "version": f"{upstream_version}+{pin}.{th}",
        "synced_on": (today or dt.datetime.now(dt.timezone.utc).date()).isoformat(),
        "groups": cfg.enabled_groups,
        "excluded": sorted(cfg.excluded),
        "owned": list(OWNED),
        "files": dict(sorted(hashes.items())),
    }
    warnings = []
    if snap.commit is None:
        warnings.append(f"source is an unpinned {snap.kind}; the lock records no commit")
    if snap.plugin_version is None:
        warnings.append("source has no readable .claude-plugin/plugin.json; upstream version recorded as 0.0.0")
    total = sum(len(b) for b in files.values())
    if total > cfg.max_tree_bytes:
        problems.append(f"selected tree is {total} bytes, over the {cfg.max_tree_bytes}-byte budget (NFR-005)")
    has_commands = any(p.startswith(".claude/commands/") for p in files)
    owned = {".claude-plugin/plugin.json": overlay_manifest(cfg, lock, has_commands),
             "README.md": provenance_readme(cfg, lock)}
    old = (read_lock(cfg) or {}).get("files", {})
    return SyncPlan(files=files, lock=lock, owned=owned, problems=problems, warnings=warnings,
                    changes=_changes(old, hashes))


def write_sync(cfg: Config, plan: SyncPlan) -> None:
    """Write the plan atomically: build a sibling temp dir, then swap it in. Refuses a plan with problems."""
    if not plan.ok:
        raise ValueError("refusing to write a sync plan with problems: " + "; ".join(plan.problems))
    dest = cfg.vendor_dir
    dest.parent.mkdir(parents=True, exist_ok=True)
    tmp = Path(tempfile.mkdtemp(prefix=".agent-skills-", dir=dest.parent))
    try:
        for rel, data in {**plan.files, **plan.owned}.items():
            out = tmp / rel
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_bytes(data)
            os.chmod(out, 0o644)
        old = dest.with_name(dest.name + ".old")
        if old.exists():
            shutil.rmtree(old)
        if dest.exists():
            dest.rename(old)
        tmp.rename(dest)
        if old.exists():
            shutil.rmtree(old)
    finally:
        if tmp.exists():
            shutil.rmtree(tmp)
    cfg.lock_path.write_text(dump_json(plan.lock), encoding="utf-8")


def _frontmatter_problems(path: Path, rel: str) -> list[str]:
    text = path.read_text(encoding="utf-8", errors="replace")
    m = FRONTMATTER_RE.match(text)
    if not m:
        return [f"{rel}: no YAML frontmatter"]
    keys = {}
    for line in m.group(1).splitlines():
        if ":" in line and not line.startswith((" ", "\t")):
            k, v = line.split(":", 1)
            keys[k.strip()] = v.strip()
    out = [f"{rel}: frontmatter missing '{k}'" for k in ("name", "description") if not keys.get(k)]
    expected = rel.split("/")[1]
    if keys.get("name") and keys["name"] != expected:
        out.append(f"{rel}: frontmatter name {keys['name']!r} does not match its directory {expected!r}")
    return out


def _manifest_sources(cfg: Config) -> list[str]:
    """Findings for any marketplace/plugin source in the integration that is not a local relative path (AC-007)."""
    out = []
    root_mp = cfg.root / ".claude-plugin" / "marketplace.json"
    if root_mp.is_file():
        data = json.loads(root_mp.read_text(encoding="utf-8"))
        for i, plugin in enumerate(data.get("plugins", [])):
            src = plugin.get("source")
            if not (isinstance(src, str) and src.startswith("./")):
                out.append(f".claude-plugin/marketplace.json: plugins[{i}] source {src!r} is not a local relative path")
    for name in ("settings.json", "settings.local.json"):
        settings = cfg.root / ".claude" / name
        if not settings.is_file():
            continue
        data = json.loads(settings.read_text(encoding="utf-8"))
        for mp_name, spec in (data.get("extraKnownMarketplaces") or {}).items():
            src = (spec or {}).get("source", {})
            if mp_name == cfg.marketplace and src.get("source") != "directory":
                out.append(f".claude/{name}: marketplace {mp_name!r} source {src.get('source')!r} is not a local directory")
        if name == "settings.json" and cfg.marketplace in (data.get("extraKnownMarketplaces") or {}):
            out.append(".claude/settings.json: declares the marketplace path; commit only enabledPlugins "
                       "(the per-machine path belongs in settings.local.json, plan: Settings)")
    return out


def verify(cfg: Config) -> list[str]:
    """Findings for the vendored tree, lock, config and manifests. Empty list = clean. Reads only local files."""
    findings: list[str] = []
    lock = read_lock(cfg)
    vendor = cfg.vendor_dir

    for item in cfg.selection():
        if any(item == c or item.startswith(c) or c.startswith(item) for c in CONFLICTING) \
                and cfg.is_excluded(item) is None:
            findings.append(f"config: conflicting item {item} is allowlisted (REQ-007); it must stay excluded")
    for c in CONFLICTING:
        if cfg.is_excluded(c) is None:
            findings.append(f"config: conflicting item {c} is no longer in excluded (REQ-007)")

    findings += _manifest_sources(cfg)
    findings += _citations(cfg, vendored=vendor.is_dir())

    if lock is None:
        if vendor.exists():
            findings.append(f"{cfg.raw['vendor_dir']}: present but the lock {cfg.raw['lock']} is missing")
        return findings
    if not vendor.is_dir():
        findings.append(f"{cfg.raw['vendor_dir']}: missing but the lock exists")
        return findings

    locked = lock.get("files", {})
    on_disk = {p.relative_to(vendor).as_posix() for p in vendor.rglob("*") if p.is_file() or p.is_symlink()}
    for rel in sorted(on_disk - set(locked) - set(OWNED)):
        findings.append(f"{rel}: in the vendored tree but not in the lock")
    total = 0
    for rel, digest in sorted(locked.items()):
        path = vendor / rel
        if path.is_symlink() or not path.is_file():
            findings.append(f"{rel}: in the lock but missing from the vendored tree")
            continue
        data = path.read_bytes()
        total += len(data)
        if sha256(data) != digest:
            findings.append(f"{rel}: modified (hash differs from the lock); fix it in the fork and re-sync")
        if path.stat().st_mode & (stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH):
            findings.append(f"{rel}: executable bit set")
    if total > cfg.max_tree_bytes:
        findings.append(f"vendored tree is {total} bytes, over the {cfg.max_tree_bytes}-byte budget (NFR-005)")
    if "LICENSE" not in locked:
        findings.append("LICENSE: missing from the vendored tree (NFR-007)")
    if lock.get("version", "").split("+")[-1].split(".")[-1] != tree_hash(locked)[:8]:
        findings.append("lock: version stamp does not match the locked files; re-sync")

    has_commands = any(p.startswith(".claude/commands/") for p in locked)
    expected_owned = {".claude-plugin/plugin.json": overlay_manifest(cfg, lock, has_commands),
                      "README.md": provenance_readme(cfg, lock)}
    for rel, data in expected_owned.items():
        path = vendor / rel
        if not path.is_file() or path.read_bytes() != data:
            findings.append(f"{rel}: QuantSmith-owned file differs from what sync generates; re-sync, do not edit")

    for rel in sorted(locked):
        for c in CONFLICTING:
            if rel == c or rel.startswith(c):
                findings.append(f"{rel}: conflicting upstream item is vendored (REQ-007)")
        if rel.startswith("skills/") and rel.endswith("/SKILL.md") and rel.count("/") == 2 and (vendor / rel).is_file():
            findings += _frontmatter_problems(vendor / rel, rel)

    selected = cfg.selection()
    for rel in sorted(locked):
        if not any(rel.startswith(s) if s.endswith("/") else rel == s for s in selected):
            findings.append(f"{rel}: vendored but outside the current allowlist; re-sync")
    for s in selected:
        if not any(r.startswith(s) if s.endswith("/") else r == s for r in locked):
            findings.append(f"{s}: allowlisted but not vendored; re-sync")
    findings += _collisions(cfg, locked)
    return findings


def _citations(cfg: Config, vendored: bool) -> list[str]:
    """Each coding-stage agent cites at least one skill, and every citation resolves (AC-012)."""
    out = []
    allowed = set(cfg.enabled_items("skills"))
    for rel in cfg.citing_agents:
        path = cfg.root / rel
        if not path.is_file():
            out.append(f"{rel}: listed in citing_agents but missing")
            continue
        cited = set(CITATION_RE.findall(path.read_text(encoding="utf-8")))
        if not cited:
            out.append(f"{rel}: cites no vendor/agent-skills skill (REQ-009)")
        for name in sorted(cited):
            target = cfg.vendor_dir / "skills" / name / "SKILL.md"
            if (vendored and not target.is_file()) or (not vendored and name not in allowed):
                out.append(f"{rel}: cites skill {name!r}, which is not {'vendored' if vendored else 'allowlisted'}")
    return out


def _collisions(cfg: Config, locked: dict) -> list[str]:
    """Upstream skill/persona names that equal a QuantSmith agent's name (RISK-005)."""
    registry = cfg.root / "agents" / "agent_registry.yaml"
    if not registry.is_file():
        return []
    ours = {m.split("/")[-1] for m in re.findall(r'^  - name: "([^"]+)"', registry.read_text(encoding="utf-8"), re.MULTILINE)}
    theirs = {p.split("/")[1] for p in locked if p.startswith("skills/")}
    theirs |= {Path(p).stem for p in locked if p.startswith("agents/")}
    return [f"name collision: upstream {n!r} matches a QuantSmith agent" for n in sorted(theirs & ours)]
